CREATE TABLE IF NOT EXISTS STUDENT( 
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
  , NAME VARCHAR (60) NOT NULL
  , AGE BIGINT NOT NULL
  , STATUS BIGINT NOT NULL
  , DEPARTMENT_ID BIGINT NOT NULL
  , EMAIL VARCHAR (254) NOT NULL
);
